site_name: Chenxing Luo
theme:
  name: null
  custom_dir: blanc
copyright: 2022, Chenxing
markdown_extensions: 
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - mdx_urlize
  - markdown_captions
  - attr_list