site_name: Chenxing Luo
site_author: Chenxing Luo
site_description: Chenxing Luo's homepage and academic notes
site_analytics:
  google: G-HVVEZZZNJV

theme:
  name: null
  custom_dir: blanc
copyright: 2022, Chenxing
markdown_extensions: 
  - smarty
  - pymdownx.arithmatex:
      preview: false
  - pymdownx.magiclink
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.keys
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - markdown_captions
  - attr_list

plugins:
  - search
  - compile_sass
  - mkdocs_wikilinks_enabler
  - mkdocs_subpages
  - mkdocs_blogging
  - jinja2_load_extensions:
      extensions:
        - jinja2_time.TimeExtension
        - jinja2.ext.loopcontrols
  - minify:
      minify_html: true